### ISSUE TITLE
Provide better description for each commit again

### ISSUE THREAD

**Issue by peterennisrda** [kinsidar/Association-Contacts#18]
Describe all your changes as atomic commits where possible, i.e. do not
use duplicate commits message.
![capture1190](https://user-images.githubusercontent.com/1280523/32400548-daa91eb8-c0be-11e7-838a-215795c02c65.PNG)

**Comment by kinsidar** [comment]
It seems that when I save edits made on gitbook editor, it will commit the changes automatically:

<img width="1169" alt="gitbook bot commits" src="https://user-images.githubusercontent.com/13373809/32421626-5d3bb818-c24f-11e7-87f5-f9b859beafd3.png">

**Comment by peterennisrda** [comment]
Check if you can control this.
Open a ticket with gitbook if needed.
Add the Q&A to DFAQ.

**Comment by kinsidar** [comment]
It doesn't seem as if I can control this, I've created an issue:

https://github.com/GitbookIO/gitbook/issues/1911

**Comment by peterennisrda** [comment]
Can you edit with VS Code instead and use that to commit?

**Comment by kinsidar** [comment]
Yes I edit it VS Code most of the time, but some things like adding links
that direct to local articles were more easy in gitbook editor, which is
why I used it.

I noticed that gitbook editor makes a commit whenever I save, so if I
happen to use the editor again I will make all the necessary changes before
saving the file to keep the commits minimal.

**Comment by zq99299** [comment]
是啊。 编辑器这个保存自动提交，太蛋疼了。 而且还莫名其妙的丢失文件。


Yes. Editor save this automatically submitted, too egg hurt. But also somehow lost the file.

**Comment by peterennisrda** [comment]
@kinsidar, Do you understand this comment?

**Comment by kinsidar** [comment]
@peterennisrda I can understand bits and pieces, not much better than the auto translation haha.

He agreeing and saying that the gitbook editor automatically commits, which is a pain in the ass.  And he says that files go missing for no reason.

**Comment by kinsidar** [comment]
@zq99299 对，在gitbook我写了一个问题: https://github.com/GitbookIO/gitbook/issues/1911

我不知道怎么办·， 我使用gitbook-cli建立我的gitbook (https://kinsidar.github.io/DFAQ/documentation/host-gitbook-on-github.html)

**Comment by zq99299** [comment]
@peterennisrda @kinsidar 

哈哈哈，不懂英文，希望你们能看懂。英文都是我机器翻译贴出来的，


好多编辑器都是可以手动保存的，而不是每次都调用 git commit，只要调用git commit，那么就意味着提交。包括我们平时开发代码也是如此，临时保存是编辑器的功能，最终决定什么时候提交给git是由我们自己决定的。

然而现状是：gibook编辑器的文档保存全部依赖git commit。编辑器里面有提供一个自动提交是否打开的功能，但是一但关闭，每次保存都会弹出一个对话框给我，让我选择或则填写提交信息。这个就太繁琐了。

gitbook编辑器现在提供的自动提交模式我在使用的几个月中，还发现文件老是莫名其妙的丢失。


----------------------------


Ha ha ha, do not understand English, I hope you can understand. English is posted on my machine translation,


Many editors can be manually saved, rather than calling git commit each time, as long as the call git commit, then it means submit. Including our usual development code as well, temporary preservation is the editor's function, the final decision when to submit to git is our own decision.

However, the status quo is: The gibook editor's documentation depends entirely on git commit. Editor provides a function to automatically submit whether to open, but once closed, each save will pop up a dialog box to me, let me choose or fill in the submission information. This is too cumbersome.

The automatic submission mode that the gitbook editor now offers I've been using the files for a few more months and also found that files are always bafflingly lost.
